
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar Inzunsa
 */
public class Programa extends javax.swing.JFrame {
    int tamaño=0;
    int[] arregloAux;
    Matriz objeto;
    
    public Programa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnGenerarMatriz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTriangularSuperior = new javax.swing.JButton();
        btnTriangularSuperiorInvertida = new javax.swing.JButton();
        btnTriangularInferior = new javax.swing.JButton();
        btnTriangularInferiorInvertida = new javax.swing.JButton();
        btnVerMatriz = new javax.swing.JButton();
        btnDiagonal = new javax.swing.JButton();
        btnDiagonalInvertida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tamaño");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnGenerarMatriz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGenerarMatriz.setText("Generar Matriz");
        btnGenerarMatriz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarMatrizMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnTriangularSuperior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTriangularSuperior.setText("Triangular Superior");
        btnTriangularSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTriangularSuperiorMouseClicked(evt);
            }
        });

        btnTriangularSuperiorInvertida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTriangularSuperiorInvertida.setText("Triangular Superior Invertida");
        btnTriangularSuperiorInvertida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTriangularSuperiorInvertidaMouseClicked(evt);
            }
        });

        btnTriangularInferior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTriangularInferior.setText("Triangular Inferior");
        btnTriangularInferior.setToolTipText("");
        btnTriangularInferior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTriangularInferiorMouseClicked(evt);
            }
        });

        btnTriangularInferiorInvertida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTriangularInferiorInvertida.setText("Triangular Inferior Invertida");
        btnTriangularInferiorInvertida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTriangularInferiorInvertidaMouseClicked(evt);
            }
        });

        btnVerMatriz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVerMatriz.setText("Ver matriz");
        btnVerMatriz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMatrizMouseClicked(evt);
            }
        });

        btnDiagonal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDiagonal.setText("Diagonal");
        btnDiagonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDiagonalMouseClicked(evt);
            }
        });

        btnDiagonalInvertida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDiagonalInvertida.setText("Diagonal Invertida");
        btnDiagonalInvertida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDiagonalInvertidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTriangularSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(btnGenerarMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTriangularInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTriangularSuperiorInvertida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDiagonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDiagonalInvertida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTriangularInferiorInvertida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerarMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTriangularSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTriangularInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTriangularSuperiorInvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTriangularInferiorInvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDiagonal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDiagonalInvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagonalInvertidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiagonalInvertidaMouseClicked
        // Diagonal invertida
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();

        arregloAux = objeto.obtenerDiagonalInvertida();
        model2.setRowCount(1);
        model2.setColumnCount(arregloAux.length);

        for(int i=0; i<arregloAux.length; i++){
            jTable1.setValueAt(arregloAux[i], 0, i);
        }
    }//GEN-LAST:event_btnDiagonalInvertidaMouseClicked

    private void btnDiagonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiagonalMouseClicked
        // Diagonal
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();

        arregloAux = objeto.obtenerDiagonal();
        model2.setRowCount(1);
        model2.setColumnCount(arregloAux.length);

        for(int i=0; i<arregloAux.length; i++){
            jTable1.setValueAt(arregloAux[i], 0, i);
        }
    }//GEN-LAST:event_btnDiagonalMouseClicked

    private void btnVerMatrizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMatrizMouseClicked
        // ver matriz
        mostrarMatriz(objeto.getMatriz());
    }//GEN-LAST:event_btnVerMatrizMouseClicked

    private void btnTriangularInferiorInvertidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTriangularInferiorInvertidaMouseClicked
        // Matriz inverior inversa
        mostrarMatriz(objeto.obtenerTriangularInferiorInversa());
    }//GEN-LAST:event_btnTriangularInferiorInvertidaMouseClicked

    private void btnTriangularInferiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTriangularInferiorMouseClicked
        // Matriz inferior
        mostrarMatriz(objeto.obtenerTriangularInferior());
    }//GEN-LAST:event_btnTriangularInferiorMouseClicked

    private void btnTriangularSuperiorInvertidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTriangularSuperiorInvertidaMouseClicked
        // Matriz superior inversa
        mostrarMatriz(objeto.obtenerTriangularSuperiorInversa());
    }//GEN-LAST:event_btnTriangularSuperiorInvertidaMouseClicked

    private void btnTriangularSuperiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTriangularSuperiorMouseClicked
        // Matriz superior
        mostrarMatriz(objeto.obtenerTriangularSuperior());
    }//GEN-LAST:event_btnTriangularSuperiorMouseClicked

    private void btnGenerarMatrizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMatrizMouseClicked

        try{
            tamaño = Integer.parseInt(jTextField1.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ERROR: "+e);
        }
        objeto = new Matriz(tamaño);
        mostrarMatriz(objeto.getMatriz());
    }//GEN-LAST:event_btnGenerarMatrizMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }
    
    public void mostrarMatriz(int[][] matriz){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(matriz.length);
        model.setColumnCount(matriz.length);
        
        for(int i=0; i<matriz.length; i++){
            for(int j=0; j<matriz.length; j++){
                jTable1.setValueAt(matriz[i][j], i, j);
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagonal;
    private javax.swing.JButton btnDiagonalInvertida;
    private javax.swing.JButton btnGenerarMatriz;
    private javax.swing.JButton btnTriangularInferior;
    private javax.swing.JButton btnTriangularInferiorInvertida;
    private javax.swing.JButton btnTriangularSuperior;
    private javax.swing.JButton btnTriangularSuperiorInvertida;
    private javax.swing.JButton btnVerMatriz;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
